### ISSUE TITLE
problem about the code

### ISSUE THREAD

**Issue by Ekko-yan** [wentian-zhao/entity-aware-caption#1]
Hello, after I installed all the packages here, I used python train.py to run it, and the following error occurred. Is it correct to use python train.py to execute the statement? How to run this code?

$ python train.py
cli_main
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    cli_main()
  File "/root/anaconda3/envs/ysy/lib/python3.8/site-packages/fairseq_cli/train.py", line 346, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/root/anaconda3/envs/ysy/lib/python3.8/site-packages/fairseq/options.py", line 139, in parse_args_and_arch
    raise RuntimeError()
RuntimeError

**Comment by youxiaoxing** [comment]
I encountered the same problem. Did you solve it?

**Comment by youxiaoxing** [comment]
Run using the following command. Note to remove the "/"
python train.py --user-dir . --task caption --save-dir ../checkpoint --arch lstm --batch-size 48 --optimizer adam --lr 1e-4  --criterion adaptive_loss --adaptive-softmax-cutoff 5000,20000 --ddp-backend=no_c10d
